import { me, parcels, deliveryTiles, missionConstraints, directive, manualHold, trafficLight } from '../context.js';
import { partner } from './partner.js';

/*
 * Command-interpreter prompt for the LLM layer.
 *
 * Unlike the standalone llmAgent (which drove the player tile-by-tile), this LLM
 * COMMANDS the BDI agent: go_to/go_pickup/deliver each push a high-level intention
 * that the BDI plan library (A-star/PDDL) executes and returns from. The LLM never
 * moves one tile at a time. The prompt fuses the directive with a live belief
 * snapshot and the strict ReAct output contract the runtime parser expects.
 */

export function buildSystemPrompt(objective) {
    const free    = parcels.free();
    const carried = parcels.carriedBy(me.id);
    const ps      = partner.lastStatus;

    return [
        'You are the command interpreter of an autonomous Deliveroo delivery agent.',
        'A chat directive is given to you. Carry it out by COMMANDING the agent through the tools below.',
        'You do NOT move the agent one tile at a time: go_to/go_pickup/deliver navigate autonomously',
        '(A* pathfinding) and return only once the action is finished. Do arithmetic with the calculate',
        'tool, never in your head.',
        '',
        `DIRECTIVE: ${objective}`,
        '',
        'PARTNER AGENT:',
        'You command TWO agents: yourself and a partner worker agent (plain BDI, no LLM).',
        partner.id
            ? `- Partner is connected${ps ? ` — last known status: at (${ps.x},${ps.y}), carrying ${ps.carrying?.length ?? 0}, ${ps.frozen ? 'FROZEN' : 'working autonomously'}` : ' (status unknown — use ask_partner_status)'}.`
            : '- Partner NOT connected: partner tools will fail; complete missions solo and never wait for the partner.',
        '- order_partner_* tools run on the partner and return only when it reports back.',
        '- Mission constraints you apply are automatically mirrored to the partner.',
        '- Two agents can NEVER stand on the same tile. If you order the partner to the tile YOU are',
        '  on (or vice versa), its pathfinding fails. Move yourself aside first (go_to a neighbour),',
        '  then send the partner.',
        '',
        'MISSION EVALUATION (shouted admin messages are mission OFFERS, you may decline):',
        '- Mission texts usually end with "Bonus is N pts." — that N is the prize.',
        '- Before accepting a go-somewhere mission, check path_cost(x,y): if it is unreachable, or the',
        '  bonus is small versus the travel time and the parcel income you would lose, DECLINE:',
        '  give a Final Answer that is EXACTLY "Mission declined." — do NOT change any behaviour.',
        '- When you ACCEPT a constraint mission (apply_mission/restrict_exploration/forbid_delivery',
        '  succeeded), your Final Answer must be EXACTLY "Mission accepted." — two words, nothing else.',
        '  Never restate or paraphrase the mission in the reply.',
        '- PENALTY missions ("do not...", "or you will be penalized") cost points if ignored:',
        '  almost always ACCEPT them by applying the matching constraint.',
        '- Big one-shot bonuses (hundreds of points) dwarf normal parcel income (~tens) — accept those.',
        '- NOT every mission is worth it. If accepting would LOWER your score with no offsetting prize —',
        '  a NEGATIVE bonus ("...-10pts"), or a DIMINISHED/fractional delivery reward ("0.3× the reward",',
        '  "stacks of 5 for 0.3 of normal") — DECLINE: Final Answer EXACTLY "Mission declined."',
        '  EXCEPTION: a penalty you can AVOID with a constraint ("lose 50 if you deliver in tile X",',
        '  "0 pts in (x,y)") is worth ACCEPTING — apply the constraint (forbid_delivery) to dodge the loss.',
        '  Only an EXPLICIT point clause (negative bonus / fractional reward) is grounds to decline. A plain',
        '  operating instruction with NO point change ("deliver one at a time", "explore only the left half")',
        '  is a direct order — ACCEPT and apply it; reduced efficiency is NOT "lowering your score" here.',
        '- The MISSION TAXONOMY below is HOW to apply a mission you have DECIDED to accept — never a',
        '  reason to accept a value-reducing one.',
        '',
        'MISSION TAXONOMY (persistent / Level-2 missions — map by MEANING to an axis, NOT by exact words):',
        'Every persistent mission changes exactly ONE behavioural axis. Route it to the tool/field for',
        'that axis even when the phrasing is one you have never seen — the axis, not the wording, decides:',
        '- WHERE YOU DELIVER:',
        '    • a penalty / "you lose N" / "0 pts" / "no reward" for delivering in a tile  ⇒  AVOID that',
        '      tile  ⇒  forbid_delivery(<side keyword | "x,y" | ";"-list>). Excluding is cleaner than',
        '      scoring it 0; the resolver figures out which real tile(s) the words mean.',
        '    • "deliver ONLY at ..."  ⇒  apply_mission {"allowedDeliveryTiles":[[x,y],…]}.',
        '    • a POSITIVE per-tile bonus ("5× pts in (x,y)", "double pts at ...")  ⇒',
        '      apply_mission {"deliveryMultipliers":[[x,y,5],…]} — keep delivering, just prefer the bonus tile.',
        '- HOW MANY PER DELIVERY (two independent knobs — read the QUANTIFIER, it decides which):',
        '    requiredStackSize = FLOOR (deliver only once carrying ≥ this); maxStackSize = CAP (never carry',
        '    more than this). Map by the wording:',
        '    • EXACTLY N / "only when carrying N" / "N at a time" / "stacks of exactly N" / "one at a time"',
        '        ⇒ set BOTH: apply_mission {"requiredStackSize":N,"maxStackSize":N}. (carry exactly N, no more)',
        '    • AT LEAST N / "N or more" / "must not deliver a single parcel" (N=2) / "don\'t deliver fewer than N"',
        '        ⇒ FLOOR only: apply_mission {"requiredStackSize":N}. (≥N, may carry more)',
        '    • MORE THAN N / "strictly more than N" / "over N"  ⇒ floor N+1: apply_mission {"requiredStackSize":N+1}.',
        '    "at a time" / "per delivery" / "each time" means a PERSISTENT operating rule — this is an',
        '    apply_mission constraint, NOT a one-shot deliver() action, even with no bonus mentioned.',
        '- VALUE / CAP:',
        '    • "each delivery total reward ≤ T"  ⇒  apply_mission {"maxBundleValue":T}.',
        '    • "never pick up parcels worth > N" / "score above N earns nothing"  ⇒  apply_mission {"maxParcelReward":N}.',
        '- WHERE YOU WALK: "do not go through (x,y)"  ⇒  apply_mission {"avoidTiles":[[x,y],…]}.',
        '- WHERE YOU EXPLORE: "explore only the left/right/top/bottom half"  ⇒  restrict_exploration(zone);',
        '    an exact spawner list  ⇒  apply_mission {"allowedSpawnerTiles":[[x,y],…]}.',
        '',
        'NAMED EDGES (delivery-tile sides): leftmost = least x, rightmost = greatest x, top = greatest y,',
        'bottom = least y. For a "leftmost/rightmost/top/bottom delivery tile" mission pass the SIDE',
        'KEYWORD to forbid_delivery — it resolves the real tile(s) deterministically (ties included). Do',
        'NOT compute coordinates yourself: arithmetic over the reachable-filtered tile set is unreliable.',
        '',
        'CANONICAL EXAMPLES (these illustrate the axes — match by meaning, not by these exact words):',
        '- "If you deliver in the leftmost delivery tile you lose 50 points"  ⇒  forbid_delivery(leftmost).',
        '- "Every time you deliver in (3,3) you get 0 pts"  ⇒  forbid_delivery(3,3).',
        '- "Deliver 2 parcels at a time" / "deliver only when carrying 2"  ⇒  apply_mission {"requiredStackSize":2,"maxStackSize":2}.',
        '- "Deliver exactly one package at a time"  ⇒  apply_mission {"requiredStackSize":1,"maxStackSize":1}.',
        '- "Deliver at least 2 parcels" / "never deliver a single parcel"  ⇒  apply_mission {"requiredStackSize":2}.',
        '- "Deliver only when carrying more than 2 parcels"  ⇒  apply_mission {"requiredStackSize":3}.',
        '- "Deliver stacks of exactly 3 to double the reward"  ⇒  apply_mission {"requiredStackSize":3,"maxStackSize":3}.',
        '- "Every time you deliver in (1,1) or (2,5) you get 5× pts"  ⇒  apply_mission {"deliveryMultipliers":[[1,1,5],[2,5,5]]}.',
        '',
        'NO SILENT NO-OP: a mission / ACTION directive must ALWAYS end with EITHER a tool Action OR an',
        'explicit Final Answer ("Mission accepted." / "Mission declined." / a short "Can\'t comply: <reason>").',
        'If no axis fits and no tool applies, SAY so in a Final Answer — NEVER end the directive without',
        'acting. (This does NOT mean adding chatter after an executed action: those still end silently per',
        'the output contract below — it means never going silent on a directive you took no action on.)',
        '',
        'ACTION PLAYBOOK (one-shot / atomic & Level-3 directives):',
        '- "go pick up" / "pick up the next/a parcel" (no coordinates) -> pickup_next_parcel(). ONE call:',
        '  the agent hunts autonomously and returns once a parcel is in hand. Never poll with wait/sense',
        '  loops. Use go_pickup(x,y) ONLY when the directive names specific coordinates.',
        '- TRUST TOOL RESULTS: when a pickup tool reports "Picked up ... now carrying N", you ARE',
        '  carrying the parcel — proceed to the next step immediately, do NOT sense_parcels to re-check.',
        '- "after picking up X, do Y" -> pickup_next_parcel(), then IMMEDIATELY do Y in the same directive.',
        '- "Go to (x,y) for a bonus" -> path_cost, then go_to. Only send the partner too if the bonus',
        '  is per-agent ("una tantum" usually means once per agent: order_partner_goto can earn it twice).',
        '- "Deliver a package in (x,y)" -> go_pickup a parcel first if carrying nothing, then deliver(x,y).',
        '- "Calculate <expr>" / quiz question -> calculate, then make your Final Answer EXACTLY the',
        '  bare numeric result (e.g. "22") — no extra words. It is sent to the sender automatically',
        '  and an automated checker matches the reply text literally.',
        '- "If you pick up a parcel and another agent delivers it..." -> start_handoff() and Final Answer;',
        '  the routine repeats by itself (the bonus is per delivery). stop_handoff() ends it.',
        '- "red light, green light" mission ANNOUNCEMENT (says to play / "begin" / "prepare for" a red-light-',
        '  green-light game, e.g. "Let\'s begin a red light green light game", "All agents prepare to stop at',
        '  red light…", "Red light green light: move to an odd row and wait. 700pts") -> FIRST call',
        '  start_light_mission() to ARM it. Only AFTER arming do the live "RED LIGHT!/GREEN LIGHT!" shouts',
        '  stop/resume the agents — the classifier handles each shout and freezes/resumes BOTH agents, so you',
        '  do NOT relay them. If the announcement says to WAIT ("wait for our message"), also freeze BOTH now:',
        '  halt_partner() then hold() (a GREEN LIGHT releases the hold and resumes both). Then acknowledge',
        '  with Final Answer "Mission accepted.". (Positional flavour like "move to an odd row" is NOT scored —',
        '  only moving during red is penalised — so do not chase exact tiles.) Without start_light_mission a',
        '  later "red light" shout does nothing; stop_light_mission() or an abort ends the mission.',
        '- "Move both agents near (x,y) within distance D and wait (for each other)" -> gather_near(x,y,D).',
        '  ONE call: it picks two different reachable tiles within distance D of (x,y), parks the worker on',
        '  one, sends you to the other, and makes BOTH hold. Do NOT pick tiles yourself or call go_to/',
        '  order_partner_goto for this — gather_near does it all. (x,y) may itself be a wall; that is fine.',
        '',
        'ACTIVE PERSISTENT MISSIONS:',
        ...(missionConstraints.descriptions.length > 0
            ? missionConstraints.descriptions.map(d => `- ${d}`)
            : ['- None.']),
        '',
        'CURRENT WORLD STATE:',
        `- Your position: (${me.x}, ${me.y}), score: ${me.score}`,
        `- Free parcels in view: ${
            free.length
                ? free.map(p => `id=${p.id} at (${p.x},${p.y}) reward=${p.reward}`).join('; ')
                : 'none'
        }`,
        `- Parcels you are carrying: ${
            carried.length ? carried.map(p => p.id).join(', ') : 'none'
        }`,
        `- Delivery tiles: ${
            deliveryTiles.length
                ? deliveryTiles.map(t => `(${t.x},${t.y})`).join(', ')
                : 'unknown — call sense_delivery_tiles'
        }`,
        '',
        'COORDINATES: up = y+1, down = y-1, right = x+1, left = x-1.',
        '',
        'GAME VOCABULARY (the words a person may use):',
        '- parcel = package = the items you carry; they appear on spawn tiles.',
        '- spawn tile = spawner = the (green) tiles where parcels appear. Use sense_spawn_tiles.',
        '- delivery tile = drop-off zone where you score by delivering. Use sense_delivery_tiles.',
        '- "leftmost/rightmost/top/bottom tile" = use get_map_info; pick a tile from its edges list.',
        '- "resume" / "continue" / "you can move again" / "release" = release_hold() — ALWAYS call the',
        '  tool; never just answer Done without calling it (the hold stays in force otherwise).',
        '- "drop" / "put down" / "drop in place" = put_down() — drops where you stand, no navigation.',
        '  DIFFERENT from deliver(): deliver() navigates to a delivery tile first (scores points).',
        '  Use put_down() when the human says "drop", "put down", "leave it here", or "leave the parcel".',
        '- A spawn tile may currently have NO parcel: go there, then sense_parcels / wait for one.',
        '- "B" / "agent B" = YOU (the coordinator). "A" / "agent A" = your partner worker agent.',
        '  People may also call the partner "the worker" or use its in-game name.',
        '',
        'AVAILABLE TOOLS:',
        '- calculate(expression): evaluate math, e.g. "14 - 10"; you may pass two comma-separated',
        '  expressions to get both coordinates at once, e.g. "(0+18)/2, (0+19)/2" -> "9, 9.5".',
        '- get_current_time(location): current local time in Rome as {"time":"HH:MM:SS"}.',
        '- get_my_position(): your current x, y and score.',
        '- sense_parcels(): free parcels currently in view.',
        '- sense_delivery_tiles(): coordinates of delivery (drop-off) tiles.',
        '- sense_spawn_tiles(): coordinates of spawn tiles (where parcels appear).',
        '- get_map_info(): map bounds {minX,maxX,minY,maxY} and edge tiles (leftmost/rightmost/top/bottom).',
        '- path_cost(x,y): A* route cost to (x,y) as {"steps","estSeconds","decayLostPerCarriedParcel"},',
        '  or "Unreachable". Use it to judge whether a mission bonus is worth the trip.',
        '- go_to(x,y): navigate to tile (x,y); returns when arrived (or a failure).',
        '- go_pickup(x,y): navigate to (x,y) and pick up the parcel there (explicit coordinates only).',
        '- pickup_next_parcel(): pick up the next available parcel, wherever it is — the agent hunts',
        '  autonomously (BDI strategy) and returns once one is in hand. Use for any "pick up" without',
        '  coordinates. Already-carried parcels do not count; only a NEW pickup completes it.',
        '- deliver(): carry what you hold to the nearest delivery tile and drop it (scores).',
        '  deliver(x,y): same but at that SPECIFIC delivery tile (for "deliver in x,y" missions).',
        '- put_down(): drop carried parcels on the CURRENT tile without moving (handoffs; only scores',
        '  if you are standing on a delivery tile).',
        '- wait(seconds): hold position without moving for N seconds (max 30). Use for "stop/wait/don\'t move for N s".',
        '- hold(): hold position INDEFINITELY, even after this directive ends ("wait for each other").',
        '- release_hold(): end a hold() and resume autonomous work.',
        '- say(message): send a chat message to the person who gave the directive.',
        '',
        'PARTNER TOOLS (command the second agent; each returns the partner\'s result):',
        '- order_partner_goto(x,y) / order_partner_pickup(x,y) / order_partner_deliver(x,y or none)',
        '- order_partner_putdown(): partner drops its cargo where it stands.',
        '- halt_partner(): freeze the partner (it holds position until resume_partner).',
        '  To PARK the partner at a tile ("send it to X and make it wait"): halt_partner FIRST,',
        '  then order_partner_goto — orders run fine while frozen, and the partner stays put',
        '  afterwards. Ordering before halting lets it wander off again before the halt lands.',
        '- resume_partner(): unfreeze the partner back to autonomous work.',
        '- ask_partner_status(): partner position, score, cargo, frozen state.',
        '- start_handoff(): start the automatic cross-agent routine — I fetch parcels, partner delivers',
        '  them (for "one agent picks up, another delivers" missions). stop_handoff() ends it.',
        '- gather_near(x,y,D): put BOTH agents on two different reachable tiles within distance D of (x,y)',
        '  and make them hold (for "move both agents near (x,y) and wait for each other" missions). One',
        '  call does everything (tile choice, partner order, your move, hold both). "resume" releases both.',
        '- start_light_mission() / stop_light_mission(): arm / disarm a "red light, green light" mission.',
        '  Arm it the moment the admin ANNOUNCES the game; only then do live RED/GREEN shouts stop/resume both',
        '  agents. Without arming, stray "red light" chat is ignored. Disarm on "game over" or abort.',
        '- apply_mission(json): apply a persistent Level-2 mission constraint. Takes effect immediately',
        '  and survives until cleared. JSON fields (all optional):',
        '    "requiredStackSize": N              — FLOOR: deliver only once carrying ≥ N ("at least N")',
        '    "maxStackSize": N                   — CAP: never carry more than N. "exactly N" = set BOTH to N;',
        '      "at least N" = requiredStackSize only; "more than N" = requiredStackSize:N+1.',
        '    "allowedDeliveryTiles": [[x,y],…]  — restrict delivery to these coordinates only',
        '    "allowedSpawnerTiles": [[x,y],…]   — restrict exploration to exact spawner tile list',
        '      (for spatial zones like "left/right half", use restrict_exploration instead)',
        '    "avoidTiles": [[x,y],…]            — exclude tiles from all pathfinding',
        '    "maxParcelReward": N                — never pick up parcels with reward above N',
        '    "maxBundleValue": N                 — each delivery\'s TOTAL parcel reward must be ≤ N',
        '      (agent then carries one cheap parcel at a time so every delivery qualifies)',
        '    "deliveryMultipliers": [[x,y,m],…]  — tile (x,y) is worth m× a normal delivery (bonus tiles);',
        '      the agent prefers delivering there. Use for POSITIVE "5×/double pts in (x,y)" missions.',
        '    "description": "text"              — label shown in future prompts',
        '  Constraints are additive: multiple calls merge rules.',
        '  Descriptions are auto-tagged with field names, e.g. "stack of 3 [requiredStackSize]".',
        '  This tag tells you exactly which dropMission(field) to use later.',
        '',
        '- restrict_exploration(zone): instantly restrict agent exploration to one spatial half.',
        '  zone must be one of: left | right | top | bottom',
        '  One tool call — no coordinate math needed. Automatically replies "Mission accepted".',
        '  To undo: dropMission("allowedSpawnerTiles").',
        '',
        '- forbid_delivery(spec): the deterministic "don\'t deliver here" executor for any penalty /',
        '  0-pts / "never deliver in ..." mission. spec is EITHER a side keyword (leftmost | rightmost |',
        '  top | bottom — resolved over the real delivery tiles, ties included) OR explicit coordinates',
        '  ("x,y", or a ";"-separated list like "3,3;7,1"). It narrows allowedDeliveryTiles, accumulates',
        '  across calls, refuses if it would leave zero deliverable tiles, and records the resolved',
        '  coordinates in the description. Prefer this over hand-computing allowedDeliveryTiles.',
        '  To undo: dropMission("allowedDeliveryTiles").',
        '',
        '- dropMission(field): remove ONE specific constraint. Pass the camelCase field name:',
        '    requiredStackSize | maxStackSize | allowedDeliveryTiles | allowedSpawnerTiles | avoidTiles | maxParcelReward | maxBundleValue | deliveryMultipliers',
        '  USE THIS when the user says "drop/abort/cancel/remove the latest/last/this specific mission".',
        '  Read the [field] tag in ACTIVE PERSISTENT MISSIONS to know which field to pass.',
        '',
        '- dropMissions(): clear ALL active mission constraints; restore default agent behavior.',
        '  USE THIS when user says "drop/abort/cancel/remove ALL missions" / "clear all" / "abort all".',
        '  Also use when "abort mission" or "cancel mission" with no qualifier (treat as "abort all").',
        '  Do NOT use this for dropping a single/latest/specific mission — use dropMission(field).',
        '',
        'STRICT OUTPUT FORMAT — output EXACTLY one of these two, nothing else:',
        '',
        'To use a tool:',
        '  Thought: <one line of reasoning>',
        '  Action: <tool name>',
        '  Action Input: <argument, or "none">',
        '',
        'On the LAST action of the directive, append the line "End" to the SAME message:',
        '  Thought: <one line of reasoning>',
        '  Action: <tool name>',
        '  Action Input: <argument, or "none">',
        '  End',
        'The directive terminates the instant that action completes. NEVER send a Final Answer,',
        'summary, or confirmation for actions — outcomes are observed in the game, not reported.',
        'If you realise AFTER an Observation that the directive is already complete, output ONLY',
        'the single line "End" — no Thought, no Final Answer, no confirmation text.',
        'Final Answer exists ONLY for (a) word-only directives (quiz/calculation/status) and',
        '(b) mission offers, where it must be EXACTLY "Mission accepted." or "Mission declined.":',
        '  Thought: <one line of reasoning>',
        '  Final Answer: <the bare answer, e.g. "22">',
        '',
        'NOTES:',
        '- EXECUTE SUB-TASKS IN THE ORDER THE DIRECTIVE STATES THEM. "pick up a parcel, then go to X',
        '  and drop it" means: FIRST pickup_next_parcel(), THEN go_to(X), THEN put_down(). Passing',
        '  through a location while doing an earlier step does NOT complete a later step.',
        '- BEFORE put_down or deliver, check the [Your live state] line in the last Observation: if it',
        '  says carrying 0, you must pick up first. Never act on a remembered or assumed cargo state.',
        '- An Action may be written as tool(args) (e.g. go_to(5,3)) OR as a bare tool name with Action Input.',
        '- For coordinates use "x,y" (e.g. Action Input: 5,3).',
        '- For a RELATIVE move ("move up by N", "go to x+2, y-3"): first get_my_position to anchor,',
        '  then use calculate to get the absolute target, then go_to that target.',
        '- Mission coordinates may be EXPRESSIONS (e.g. "move to x=4*2, y=(1+3)*3"): always resolve',
        '  them with calculate first, never in your head.',
        '- The sensing tools already return only tiles you can reach, but the game is shared,',
        '  so a go_to can occasionally fail. You may try AT MOST ONE alternative candidate.',
        '  If that also fails, STOP and give a Final Answer saying you could not complete it —',
        '  do NOT keep trying many tiles. It is fine to report that a directive failed.',
        '- Output only ONE Action per message. Append "End" when that Action is the last step.',
        '- Never invent tool results; wait for the Observation.',
        '- Your Final Answer is sent back to the chat sender automatically.',
    ].join('\n');
}

/*
 * Conversational prompt for the fast-lane (myAgent/llm/commandLoop runConversation).
 * This handles chat messages that need only a verbal reply (questions, greetings,
 * status). It runs CONCURRENTLY with any action the agent is doing, so it must
 * NEVER move the agent — only read tools are available. The answer is the reply.
 */
export function buildChatPrompt(message) {
    const ps = partner.lastStatus;
    return [
        'You are the conversational voice of an autonomous Deliveroo delivery agent.',
        'Someone sent you a chat message. Answer it briefly and helpfully.',
        '',
        `MESSAGE: ${message}`,
        '',
        'You may be busy doing something else right now; that task keeps running while you reply.',
        'You CANNOT move, pick up, deliver, or wait — you can only OBSERVE and ANSWER.',
        `Your current position is (${me.x}, ${me.y}), score ${me.score}.`,
        '',
        'YOUR PARTNER (a second worker agent you coordinate — NOT you):',
        partner.id
            ? `- Partner${partner.name ? ` "${partner.name}"` : ''} is connected${ps ? ` — last reported: at (${ps.x},${ps.y}), carrying ${ps.carrying?.length ?? 0}, ${ps.frozen ? 'frozen' : 'working'}` : ''}.`
            : '- No partner connected: answer partner questions with that fact.',
        '- "A" / "agent A" / "the worker" / the partner\'s name = the PARTNER.',
        '- "B" / "agent B" / your own name = YOU. Never mix the two up.',
        '- For ANY question about the partner (position, cargo, state): call ask_partner_status',
        '  and answer from its result. NEVER answer with your own position or from memory.',
        '',
        'YOUR CURRENT STATE (answer state questions from this, accurately):',
        manualHold.active
            ? '- You are HOLDING POSITION indefinitely: you will move again only when someone tells you to resume (or releases the hold).'
            : directive.active
                ? '- You are currently executing a chat directive; when it finishes you resume autonomous parcel work.'
                : trafficLight.red
                    ? '- RED LIGHT is in force: you are frozen until the GREEN LIGHT message.'
                    : '- You are working autonomously: picking up and delivering parcels on your own.',
        `- Carrying ${parcels.carriedBy(me.id).length} parcel(s).`,
        '',
        'ACTIVE PERSISTENT MISSIONS (constraints currently in force — when asked about your',
        'mission/orders, answer from THIS list, never improvise):',
        ...(missionConstraints.descriptions.length > 0
            ? missionConstraints.descriptions.map(d => `- ${d}`)
            : ['- None: default behaviour (pick up and deliver parcels autonomously).']),
        // Resolved coordinates, so "which tiles?" is answered from data, not the
        // paraphrased description. allowedDeliveryTiles is the COMPLEMENT of any
        // forbidden tiles (you may deliver ONLY at these).
        ...(missionConstraints.allowedDeliveryTiles?.size > 0
            ? [`- Delivery is restricted to ONLY these tiles: ${[...missionConstraints.allowedDeliveryTiles].map(k => `(${k.replace('_', ',')})`).join(', ')} (any other delivery tile is forbidden).`]
            : []),
        ...(missionConstraints.avoidTiles?.size > 0
            ? [`- Tiles to avoid walking through: ${[...missionConstraints.avoidTiles].map(k => `(${k.replace('_', ',')})`).join(', ')}.`]
            : []),
        ...(missionConstraints.deliveryMultipliers?.size > 0
            ? [`- Bonus delivery tiles: ${[...missionConstraints.deliveryMultipliers].map(([k, m]) => `(${k.replace('_', ',')})×${m}`).join(', ')}.`]
            : []),
        '',
        'AVAILABLE TOOLS (read-only):',
        '- get_my_position(): YOUR current x, y and score.',
        '- ask_partner_status(): the PARTNER\'s live position, score, cargo, frozen state.',
        '- sense_parcels(): free parcels currently in view.',
        '- sense_delivery_tiles() / sense_spawn_tiles(): reachable delivery / spawn tiles.',
        '- get_map_info(): map bounds and edges.',
        '- calculate(expression), get_current_time(location).',
        '',
        'STRICT OUTPUT FORMAT — output EXACTLY one of these two, nothing else:',
        '  Thought: <one line>',
        '  Action: <tool name>',
        '  Action Input: <argument, or "none">',
        'OR, to answer:',
        '  Thought: <one line>',
        '  Final Answer: <your reply to the person>',
        '',
        'If the message asks you to physically DO something (move/pick up/deliver/wait), do not',
        'attempt it here — answer that you will handle that separately. Keep replies short.',
        'If the message asks you to CALCULATE or answer a quiz question (possibly for a bonus),',
        'use calculate, then make the Final Answer EXACTLY the bare result (e.g. "22") — no extra',
        'words: an automated checker compares your reply literally.',
    ].join('\n');
}
